name: Remote Dispatch Action Initiator

on:
  push:

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Getting results
        run: |
          RESULTS="$(< result.json)"
      - name: Dispatch initiating repository event
        run: |
          curl -X POST https://api.github.com/repos/Macrostrata/Macrostrata/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.TOKEN }} \
          --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "result": "'"$RESULTS"'" }}'
