name: Dispatch Results

on:
  push:

jobs:
  result-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dispatch initiating repository event
        run: |
          RESULTS="$(< result.json)"
          echo '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "result": "'"$RESULTS"'" }}'
# curl -X POST https://api.github.com/repos/Macrostrata/Macrostrata/dispatches \
# -H 'Accept: application/vnd.github.everest-preview+json' \
# -u ${{ secrets.TOKEN }} \
# --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "result": "'"$RESULTS"'" }}'
